---
abstract: 'Run your test suite continuously when developing.'
author:
  - 'Kang-min Liu  C<< <gugod@gugod.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.42
  YAML: 0.77
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Test::Continuous
name: Test-Continuous
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  App::Prove: 3.23
  File::ChangeNotify: 0.12
  File::Spec: 3.29
  File::Temp: 0.21
  List::MoreUtils: 0.22
  Log::Dispatch: 2.22
  Log::Dispatch::DesktopNotification: 0
  Module::ExtractUse: 0.23
  TAP::Harness: 3.16
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/gugod/Test-Continuous.git
version: 0.74
