--- 
abstract: Run your tests suite continusouly when developing.
author: Kang-min Liu  C<< <gugod@gugod.org> >>
build_requires: 
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
no_index: 
  directory: 
    - inc
    - t
requires: 
  App::Prove: 3.09
  File::Modified: 0
  Log::Dispatch: 0
  Log::Dispatch::MacGrowl: 0
  Module::ExtractUse: 0
  TAP::Harness: 3.09
  perl: 5.8.0
  self: 0.15
version: 0.0.3
