---
abstract: 'Run your tests suite continusouly when developing.'
author:
  - 'Kang-min Liu  C<< <gugod@gugod.org> >>'
build_requires:
  Test::More: 0.42
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Test::Continuous
name: Test-Continuous
no_index:
  directory:
    - inc
    - t
requires:
  App::Prove: 3.14
  Archive::Tar: 0
  File::Modified: 0
  File::Spec: 0
  File::Temp: 0
  IO::File: 0
  Log::Dispatch: 0
  Module::ExtractUse: 0
  TAP::Harness: 3.14
  TAP::Parser: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.61
