---
abstract: 'Run your tests suite continusouly when developing.'
author:
  - 'Kang-min Liu  C<< <gugod@gugod.org> >>'
build_requires:
  Test::More: 0.42
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Test::Continuous
name: Test-Continuous
no_index:
  directory:
    - inc
    - t
requires:
  App::Prove: 3.14
  Archive::Tar: 1.42
  Exporter::Lite: 0.02
  File::Modified: 0.07
  File::Spec: 3.29
  File::Temp: 0.21
  IO::File: 1.14
  Log::Dispatch: 2.22
  Module::ExtractUse: 0.23
  TAP::Harness: 3.14
  TAP::Harness::Archive: 0.12
  TAP::Parser: 3.14
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.62
